handle: stripe
isFrontendEnabled: true
name: Stripe
paymentType: purchase
settings:
  apiKey: $STRIPE_API_KEY
  publishableKey: $STRIPE_PUBLIC_KEY
  sendReceiptEmail: ''
  signingSecret: $STRIPE_WEBHOOK_SECRET
sortOrder: 99
type: craft\commerce\stripe\gateways\PaymentIntents
