description: 'Default Order PDF'
enabled: true
fileNameFormat: 'Order-{shortNumber|upper}'
handle: order
isDefault: true
language: orderLanguage
name: Default
sortOrder: 9999
templatePath: _pdf/order.html
