tabs:
  -
    fields:
      02269d9f-bbaa-4ea2-8b91-909e27e6ce05:
        required: false
        sortOrder: 10
      0ff67b0d-c811-4767-9d75-25472eee67a3:
        required: false
        sortOrder: 16
      205a826f-1701-41c7-804d-f7998cec0442:
        required: false
        sortOrder: 7
      23676c77-087c-4f52-908d-3eee1deb6004:
        required: false
        sortOrder: 6
      34358d6d-9fda-49bb-a56d-f0fe2b05027f:
        required: false
        sortOrder: 9
      4234aa0a-59b0-4777-80ee-aeb7b931b924:
        required: false
        sortOrder: 14
      4c92f946-0a98-4d19-8a70-ba643f88c1a0:
        required: false
        sortOrder: 3
      a1deff4e-43ef-4a67-870e-813cfa36700c:
        required: false
        sortOrder: 14
      a4a501f3-5e4f-4708-99e6-69599fe86b31:
        required: false
        sortOrder: 2
      b384f570-e131-42f9-8c20-8d0faacb734f:
        required: false
        sortOrder: 4
      db187b36-568c-470a-ac7c-127e3a42f8b6:
        required: false
        sortOrder: 5
      db4da419-ca41-4a13-b4a4-9c3f59c217fd:
        required: false
        sortOrder: 1
      e76f9c9f-363c-476e-ae6d-c48eed173468:
        required: false
        sortOrder: 15
      ea05b292-0026-4bec-a15c-1e09055223fc:
        required: false
        sortOrder: 8
    name: Profile
    sortOrder: 1
