fieldLayouts:
  ffe83f8d-40d2-4b1d-a320-2cbb520184b7:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: avatars
hasUrls: true
name: Avatars
settings:
  addSubfolderToRootUrl: '1'
  autoFocalPoint: ''
  bucket: $S3_AVATARS_BUCKET
  bucketSelectionMode: manual
  cfDistributionId: $S3_AVATARS_CF_DIST_ID
  cfPrefix: ''
  expires: '604800 seconds'
  keyId: $AWS_ACCESS_KEY_ID
  makeUploadsPublic: '1'
  region: $S3_BUCKET_REGION
  secret: $AWS_SECRET_ACCESS_KEY
  storageClass: ''
  subfolder: ''
sortOrder: 1
type: craft\awss3\Volume
url: $S3_AVATARS_URL
