columnSuffix: null
contentColumnType: text
fieldGroup: a773b9fb-cbc5-423a-977f-8210c987176c # Store
handle: description
instructions: ''
name: Description
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
