contentColumnType: boolean
fieldGroup: add7f1c8-5c4a-4d23-9398-8a9472f169e8
handle: enableShowcaseFeatures
instructions: ''
name: 'Enable showcase features'
searchable: true
settings:
  default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
