columnSuffix: null
contentColumnType: text
fieldGroup: 4987fb8d-cf45-4b60-a94f-51c591336558 # License
handle: notes
instructions: ''
name: Notes
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
