columnSuffix: null
contentColumnType: string
fieldGroup: a773b9fb-cbc5-423a-977f-8210c987176c # Store
handle: plugins
instructions: ''
name: Plugins
searchable: true
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craftnet\fields\Plugins
