columnSuffix: null
contentColumnType: string
fieldGroup: 4987fb8d-cf45-4b60-a94f-51c591336558 # License
handle: plugin
instructions: ''
name: Plugin
searchable: true
settings:
  allowSelfRelations: false
  limit: '1'
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craftnet\fields\Plugins
