dateModified: 1619731846
email:
  fromEmail: support@pixelandtonic.com
  fromName: 'Pixel & Tonic'
  replyToEmail: null
  template: ''
  transportSettings:
    token: $POSTMARK_TOKEN
  transportType: craftcms\postmark\Adapter
plugins:
  aws-s3:
    enabled: true
    licenseKey: null
    schemaVersion: '1.2'
    settings: null
  bugsnag:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  commerce:
    edition: pro
    enabled: true
    licenseKey: $COMMERCE_LICENSE
    schemaVersion: 3.3.2
    settings:
      activeCartDuration: PT1H
      allowEmptyCartOnCheckout: true
      autoSetNewCartAddresses: true
      cartVariable: cart
      defaultView: commerce/orders
      dimensionUnits: mm
      emailSenderAddress: ''
      emailSenderAddressPlaceholder: null
      emailSenderName: ''
      emailSenderNamePlaceholder: null
      gatewayPostRedirectTemplate: ''
      mergeLastCartOnLogin: true
      minimumTotalPriceStrategy: default
      orderPdfFilenameFormat: 'Order-{shortNumber|upper}'
      orderPdfPath: _pdf/order.html
      orderReferenceFormat: '{{number[:7]}}'
      paymentCurrency: null
      pdfAllowRemoteImages: false
      pdfPaperOrientation: portrait
      pdfPaperSize: letter
      purgeInactiveCarts: true
      purgeInactiveCartsDuration: P3M
      requireBillingAddressAtCheckout: false
      requireShippingAddressAtCheckout: false
      requireShippingMethodSelectionAtCheckout: false
      updateBillingDetailsUrl: ''
      useBillingAddressForTax: false
      validateBusinessTaxIdAsVatId: false
      weightUnits: g
  commerce-stripe:
    enabled: true
    licenseKey: null
    schemaVersion: 2.2.0
    settings: null
  mix:
    enabled: true
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  postmark:
    enabled: true
    licenseKey: null
    schemaVersion: 2.0.1
  twigpack:
    enabled: true
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  webhooks:
    enabled: true
    licenseKey: null
    schemaVersion: 2.3.0
    settings: null
system:
  edition: pro
  live: true
  name: Craftnet
  schemaVersion: 3.6.8
  timeZone: UTC
